feat: Adding Github Unittests workflow
Anti-Malware-Alliance/docubleach pull request #22
Opened 2024-06-13 09:15 UTC by lucifercr07

2024-06-13 17:14 UTC, Patterbear reviewed
I know this is the github action way of doing unit tests, but I originally wrote all the tests with pytest and I feel it was less complicated and more readable, and also because it allows for a variety of tests,.

I personally prefer a more modular, purely functional testing approach, however if @rothoma2 feels unittest and this current format you've used should be the standard, then that's all good and i'll write future tests this way.

Anyway, the actions and the tests look pretty good.

2024-06-13 17:17 UTC, Patterbear commented
Also, are force pushes ok as its lucifer07's own branch, or should we discourage them to set a standard when we have multiple people working on one branch? @rothoma2

2024-06-13 18:16 UTC, rothoma2 commented
Im not very familiar woth force pushes and multiple people on the same branch.

I think normally each one will have its own branch and you will merge one into master and then merge master into branch two before creating the second pullrequest.

In between you can always merge branch A into Branch2 if u need to pull changes into your branch.

2024-06-13 18:18 UTC, rothoma2 requested changes

2024-06-13 18:18 UTC, rothoma2 commented on .github/workflows/unit-tests.yml
> +      run: poetry run python -m unittest discover -s tests/ -p '*.py'
I think you could do this just with pytest instead of unitest

2024-06-17 19:37 UTC, rothoma2 commented
@lucifercr07  Will you change this back to use pytest, or should we drop this PullRequest? Making sure it doesnt linger for too long.

2024-06-19 19:04 UTC, merged